//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPAForum
{
    using System;
    using System.Collections.Generic;
    
    public partial class comEvent
    {
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<System.DateTime> dateCreated { get; set; }
        public Nullable<System.DateTime> dateStart { get; set; }
        public string wayPoints { get; set; }
        public string startPoint { get; set; }
        public string endPoint { get; set; }
        public string description { get; set; }
    }
}
