//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPAForum
{
    using System;
    using System.Collections.Generic;
    
    public partial class post
    {
        public int pid { get; set; }
        public int author_id { get; set; }
        public string author_name { get; set; }
        public System.DateTime post_date { get; set; }
        public string post1 { get; set; }
        public int topic_id { get; set; }
    }
}
