//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPAForum
{
    using System;
    using System.Collections.Generic;
    
    public partial class topic
    {
        public int tid { get; set; }
        public string title { get; set; }
        public string state { get; set; }
        public int starter_id { get; set; }
        public System.DateTime start_date { get; set; }
        public int forum_id { get; set; }
        public string starter_name { get; set; }
        public int views { get; set; }
        public int replies { get; set; }
    }
}
